### PR TITLE
Converts rspec's to 'expect' format using transpec tool

### PR DESCRIPTION
**Pull request by jasnow**
1. Upgraded .ruby-version to 2.3.0.
 2. Add "cache: bundler" and "sudo: false" to .travis.yml file.
 3. Used "transpec" tool to convert specs from "should" format to "expect" format.

### CODE REVIEW

**Comment by jasnow** [comment]
Created a friendly pull request.

**Comment by thesp0nge** [comment]
Hi @jasnow. Great work. I'll apply soon to either master rather than development branches

**Comment by jasnow** [comment]
thanks for update

**Comment by jasnow** [comment]
Thanks for accepting my PR.

**Pull request merged**
